# Generated by Django 2.2 on 2021-05-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_auto_20210507_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
