# Generated by Django 2.2 on 2021-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20210507_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='exibir',
            field=models.BooleanField(default=False),
        ),
    ]
