# Generated by Django 2.2 on 2021-05-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_links_exibir'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='requer_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
