# Generated by Django 2.2 on 2021-01-08 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='departamento',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Digite apenas Letras ou Números!', regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$')]),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='fone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefone deve ser no formato: '(00) 0000-0000'.", regex='^\\(\\d{2}\\)\\s\\d{4}\\-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='nome',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Digite apenas Letras ou Números!', regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$')]),
        ),
    ]
