# Generated by Django 2.2 on 2021-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsTribut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tributos',
            name='aliq',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='basered',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='mva',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='mvaaliq',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='mvaimp',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
        migrations.AlterField(
            model_name='tributos',
            name='ssimples',
            field=models.DecimalField(decimal_places=5, max_digits=19),
        ),
    ]
