# Generated by Django 2.2 on 2021-04-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsTribut', '0002_auto_20210211_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tributos_Constantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota_importados', models.DecimalField(decimal_places=5, max_digits=19)),
            ],
        ),
    ]
