# Generated by Django 2.2 on 2021-04-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsTribut', '0003_tributos_constantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tributos_Constantes',
        ),
    ]
