# Generated by Django 2.2 on 2021-05-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subsTribut', '0005_remove_tributos_aliq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tributos',
            options={'verbose_name': 'Tributo', 'verbose_name_plural': 'Tributos'},
        ),
    ]
