# Generated by Django 2.2 on 2020-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=17)),
                ('ramal', models.CharField(max_length=4)),
            ],
        ),
    ]
